 spring:
     datasource:
         url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8
         username: root
         password: root
         driver-class-name: com.mysql.jdbc.Driver


     jpa:
         database : MYSQL
         show-sql : true
         properties:
             hibernate:
                show_sql: false
                format_sql: true
                dialect: org.hibernate.dialect.MySQL5Dialect
